---
- name: Uninstall KB from Windows Server
  hosts: all
  gather_facts: false

  tasks:
    - name: Uninstall KB
      win_shell: |
        $kbNumber = "{{ KB5026362}}"
        $uninstallCommand = "wusa /uninstall /kb:$kbNumber /quiet /norestart"
        $result = Invoke-Expression -Command $uninstallCommand
        $result
      register: uninstall_result

