---
- name: Uninstall KB from Windows Server
  hosts: all
  gather_facts: false

  vars:
    kb_number: "KB5026362"

  tasks:
    - name: Get Product ID
      win_shell: 'wmic qfe where HotfixID="{{ kb_number }}" get IdentifyingNumber /value'
      register: product_id_output
      changed_when: false
      failed_when: product_id_output.rc != 0 or "IdentifyingNumber" not in product_id_output.stdout

    - name: Set Product ID fact
      set_fact:
        product_id: "{{ product_id_output.stdout | regex_search('IdentifyingNumber=(.*)', '\\1') | trim }}"

    - name: Uninstall KB
      win_package:
        product_id: "{{ product_id }}"
        state: absent

    - name: Generate CSV report template
      template:
        src: uninstall_report.j2
        dest: "C:\\temp\\uninstall_report.csv"
