---
- name: Uninstall KB from Windows Server
  hosts: all
  gather_facts: false

  vars:
    kb_number: "KB5026362"

  tasks:
    - name: Uninstall KB
      win_package:
        name: "{{ kb_number }}"
        state: absent
      register: uninstall_result

    - name: Generate CSV report template
      template:
        src: uninstall_report.j2
        dest: "C:\\temp\\uninstall_report.csv"
