---
- name: Uninstall KB from Windows Server
  hosts: windows_servers
  gather_facts: false

  vars:
    kb_number: "KB5026362"

  tasks:
    - name: Search for installed KB
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        action: search
      register: installed_updates

    - name: Get Product ID
      set_fact:
        product_id: "{{ installed_updates.updates | selectattr('kb', 'match', kb_number) | map(attribute='update_id') | first }}"

    - name: Uninstall KB
      win_package:
        product_id: "{{ product_id }}"
        state: absent

    - name: Generate CSV report template
      template:
        src: uninstall_report.j2
        dest: "C:\\temp\\uninstall_report.csv"

