---
- name: Uninstall KB from Windows Server
  hosts: all
  gather_facts: false

  tasks:
    - name: Uninstall KB
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: absent
        hotfix_id: "{{ KB5026362,kb5026363}}"
      register: uninstall_result